// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Patinaje.API.Migrations
{
    [DbContext(typeof(AppPatinContext))]
    [Migration("20250930003956_AddCamposExtra")]
    partial class AddCamposExtra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Patinaje.API.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<DateTime>("FechaClase")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("Patinaje.API.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("ClubId");

                    b.ToTable("Clubes");
                });

            modelBuilder.Entity("Patinaje.API.Models.EvaluacionTecnica", b =>
                {
                    b.Property<int>("EvaluacionTecnicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EvaluacionTecnicaId"));

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("EvaluacionTecnicaId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("Patinaje.API.Models.InscripcionTorneo", b =>
                {
                    b.Property<int>("InscripcionTorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InscripcionTorneoId"));

                    b.Property<string>("CategoriaCompetencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("CostoInscripcion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasColumnType("longtext");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("InscripcionTorneoId");

                    b.HasIndex("PatinadorId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("Patinaje.API.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkComprobante")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.Property<int>("PatinadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatinadorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AsisteGimnasio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AsisteNutricionista")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AsistePsicologo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FichaMedica")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("PatinadorId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Patinadores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("ProfesorId");

                    b.HasIndex("ClubId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Torneo", b =>
                {
                    b.Property<int>("TorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TorneoId"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaLimiteInscripcion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Organizador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TorneoId");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("Patinaje.API.Models.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("TutorId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("Patinaje.API.Models.TutorPatinador", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "PatinadorId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("TutoresPatinadores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Asistencia", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany()
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");
                });

            modelBuilder.Entity("Patinaje.API.Models.EvaluacionTecnica", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany()
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");
                });

            modelBuilder.Entity("Patinaje.API.Models.InscripcionTorneo", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany()
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patinaje.API.Models.Torneo", "Torneo")
                        .WithMany("Inscripciones")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Patinaje.API.Models.Pago", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany()
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.HasOne("Patinaje.API.Models.Club", "Club")
                        .WithMany("Patinadores")
                        .HasForeignKey("ClubId");

                    b.HasOne("Patinaje.API.Models.Profesor", "Profesor")
                        .WithMany("Patinadores")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.HasOne("Patinaje.API.Models.Club", "Club")
                        .WithMany("Profesores")
                        .HasForeignKey("ClubId");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Patinaje.API.Models.TutorPatinador", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany("Tutores")
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patinaje.API.Models.Tutor", "Tutor")
                        .WithMany("Patinadores")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Patinaje.API.Models.Club", b =>
                {
                    b.Navigation("Patinadores");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.Navigation("Patinadores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Torneo", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Patinaje.API.Models.Tutor", b =>
                {
                    b.Navigation("Patinadores");
                });
#pragma warning restore 612, 618
        }
    }
}
