// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Patinaje.API.Migrations
{
    [DbContext(typeof(AppPatinContext))]
    [Migration("20250914204038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.Property<int>("PatinadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatinadorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AsisteGimnasio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AsisteNutricionista")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AsistePsicologo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FichaMedica")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("PatinadorId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Patinadores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Relacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("TutorId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("Patinaje.API.Models.TutorPatinador", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "PatinadorId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("TutoresPatinadores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.HasOne("Patinaje.API.Models.Profesor", "Profesor")
                        .WithMany("Patinadores")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Patinaje.API.Models.TutorPatinador", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany("Tutores")
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patinaje.API.Models.Tutor", "Tutor")
                        .WithMany("Patinadores")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.Navigation("Patinadores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Tutor", b =>
                {
                    b.Navigation("Patinadores");
                });
#pragma warning restore 612, 618
        }
    }
}
