// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patinaje.API.Data;

#nullable disable

namespace Patinaje.API.Migrations
{
    [DbContext(typeof(AppPatinContext))]
    partial class AppPatinContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Patinaje.API.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<DateTime>("FechaClase")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("Asistencias", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClubId");

                    b.ToTable("Clubes", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.DetalleElemento", b =>
                {
                    b.Property<int>("DetalleElementoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetalleElementoId"));

                    b.Property<string>("CategoriaElemento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EvaluacionTorneoId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("DetalleElementoId");

                    b.HasIndex("EvaluacionTorneoId");

                    b.ToTable("DetallesElementos", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.EvaluacionTecnica", b =>
                {
                    b.Property<int>("EvaluacionTecnicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EvaluacionTecnicaId"));

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("EvaluacionTecnicaId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("EvaluacionesTecnicas", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.EvaluacionTorneo", b =>
                {
                    b.Property<int>("EvaluacionTorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EvaluacionTorneoId"));

                    b.Property<string>("ArchivoPdfUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObservacionesGenerales")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("EvaluacionTorneoId");

                    b.HasIndex("PatinadorId");

                    b.HasIndex("TorneoId");

                    b.ToTable("EvaluacionesTorneos", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.InscripcionTorneo", b =>
                {
                    b.Property<int>("InscripcionTorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InscripcionTorneoId"));

                    b.Property<string>("CategoriaCompetencia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("CostoInscripcion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("InscripcionTorneoId");

                    b.HasIndex("PatinadorId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Inscripciones", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkComprobante")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.Property<int>("PatinadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatinadorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("AsisteGimnasio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AsisteNutricionista")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AsistePsicologo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FichaMedica")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("PatinadorId");

                    b.HasIndex("ClubId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Patinadores", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProfesorId");

                    b.HasIndex("ClubId");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.Torneo", b =>
                {
                    b.Property<int>("TorneoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TorneoId"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaLimiteInscripcion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Organizador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TorneoId");

                    b.ToTable("Torneos", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Dni")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Relacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TutorId");

                    b.ToTable("Tutores", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.TutorPatinador", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("PatinadorId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "PatinadorId");

                    b.HasIndex("PatinadorId");

                    b.ToTable("TutoresPatinadores", (string)null);
                });

            modelBuilder.Entity("Patinaje.API.Models.Asistencia", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany("Asistencias")
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");
                });

            modelBuilder.Entity("Patinaje.API.Models.DetalleElemento", b =>
                {
                    b.HasOne("Patinaje.API.Models.EvaluacionTorneo", "EvaluacionTorneo")
                        .WithMany("Detalles")
                        .HasForeignKey("EvaluacionTorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluacionTorneo");
                });

            modelBuilder.Entity("Patinaje.API.Models.EvaluacionTecnica", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");
                });

            modelBuilder.Entity("Patinaje.API.Models.EvaluacionTorneo", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany()
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patinaje.API.Models.Torneo", "Torneo")
                        .WithMany()
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Patinaje.API.Models.InscripcionTorneo", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany()
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patinaje.API.Models.Torneo", "Torneo")
                        .WithMany("Inscripciones")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("Patinaje.API.Models.Pago", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany("Pagos")
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.HasOne("Patinaje.API.Models.Club", "Club")
                        .WithMany("Patinadores")
                        .HasForeignKey("ClubId");

                    b.HasOne("Patinaje.API.Models.Profesor", "Profesor")
                        .WithMany("Patinadores")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.HasOne("Patinaje.API.Models.Club", "Club")
                        .WithMany("Profesores")
                        .HasForeignKey("ClubId");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Patinaje.API.Models.TutorPatinador", b =>
                {
                    b.HasOne("Patinaje.API.Models.Patinador", "Patinador")
                        .WithMany("Tutores")
                        .HasForeignKey("PatinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patinaje.API.Models.Tutor", "Tutor")
                        .WithMany("Patinadores")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patinador");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Patinaje.API.Models.Club", b =>
                {
                    b.Navigation("Patinadores");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("Patinaje.API.Models.EvaluacionTorneo", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Patinaje.API.Models.Patinador", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Pagos");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Profesor", b =>
                {
                    b.Navigation("Patinadores");
                });

            modelBuilder.Entity("Patinaje.API.Models.Torneo", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Patinaje.API.Models.Tutor", b =>
                {
                    b.Navigation("Patinadores");
                });
#pragma warning restore 612, 618
        }
    }
}
